- name: Install required packages for caddy
  ansible.builtin.apt:
    name: "{{ caddy_packages }}"
    state: present
- name: Ensure sites enabled folder
  ansible.builtin.file:
    state: directory
    path: "{{ caddy_sites_enabled_directory }}"
    mode: "u=rwx,g=rx,o=rx"
- name: Provide Caddyfile file
  ansible.builtin.template:
    mode: "u+wr,g+r,o+r"
    src: Caddyfile.j2
    dest: "{{ caddy_caddyfile_path }}"
    # validate: /usr/bin/caddy validate --config "%s"
  notify: "Restart caddy service"
- name: Ensure caddy is running
  ansible.builtin.systemd_service:
    name: "{{ caddy_service_unit }}"
    enabled: true
    state: started
