keycloak_packages_install_recommends: true
keycloak_packages:
  - acl
  - catatonit
  - curl
  - htop
  - jq
  - passt
  - podman
  - uidmap
keycloak_username: keycloak
keycloak_uid_min: 1500
keycloak_uid_max: 1599

keycloak_pod_name: kc
keycloak_pod_file: "~/.config/containers/systemd/{{ keycloak_pod_name }}.pod"
keycloak_postgres_image: docker.io/library/postgres:18
keycloak_postgres_container_file: "~/.config/containers/systemd/{{ keycloak_pod_name }}-postgres.container"
keycloak_postgres_volume_file: "~/.config/containers/systemd/pgdata.volume"
keycloak_postgres_secrets_file: "~/.postgres.env"
keycloak_postgres_password: UNSET
keycloak_keycloak_image: quay.io/keycloak/keycloak:26.7
keycloak_keycloak_data_volume_file: "~/.config/containers/systemd/keycloak_data.volume"
keycloak_keycloak_container_file: "~/.config/containers/systemd/{{ keycloak_pod_name }}-keycloak.container"
keycloak_keycloak_secrets_file: "~/.keycloak.env"
keycloak_bootstrap_mode: false
keycloak_bootstrap_admin:
  username: admin
  password: UNSET
keycloak_publish_port: 127.0.0.1:8080
keycloak_hostname: UNSET
keycloak_export_directory: "~/exports"

keycloak_caddy_service_unit: caddy.service
keycloak_caddyfile_path: /etc/caddy/sites-enabled/keycloak.conf
keycloak_caddy_hostname: ":80"
keycloak_caddy_realms: []
keycloak_caddy_endpoint: 127.0.0.1:8080
