- name: "Reload daemon of systemd user"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
- name: "Restart postgres daemon"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
    name: kc-postgres.service
    state: restarted
- name: "Restart keycloak daemon"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
    name: kc-keycloak.service
    state: restarted
- name: Reload caddy service
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: "{{ keycloak_caddy_service_unit }}"
    state: reloaded
